version: '3.0'
services:
  db:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    environment:
      - DB_MYSQL_USER
      - DB_MYSQL_PASSWORD
      - DB_MYSQL_DATABASE
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
